"""Add 8k resolution variant

Revision ID: 1ae79cf14143
Revises: fae9fbcb64ef
Create Date: 2026-03-29 15:32:43.932272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ae79cf14143'
down_revision: Union[str, Sequence[str], None] = 'fae9fbcb64ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('image_8k_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'image_8k_url')
    # ### end Alembic commands ###
