"""Move title to categories array

Revision ID: caac42906e1c
Revises: 1ae79cf14143
Create Date: 2026-04-10 13:21:14.614970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caac42906e1c'
down_revision: Union[str, Sequence[str], None] = '1ae79cf14143'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('categories', sa.ARRAY(sa.String()), server_default='{}', nullable=False))
    op.create_index(op.f('ix_photos_categories'), 'photos', ['categories'], unique=False)
    op.drop_column('photos', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_photos_categories'), table_name='photos')
    op.drop_column('photos', 'categories')
    # ### end Alembic commands ###
